#!/bin/bash

#@title ***INSTALL***
# Install dependencies for install Google-Chrome
!sudo apt-get update > /dev/null 2>&1
!sudo apt-get install -y libu2f-udev > /dev/null 2>&1
!pip install selenium > /dev/null 2>&1

# Install Google-Chrome
!wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb > /dev/null 2>&1
!dpkg -i google-chrome-stable_current_amd64.deb > /dev/null 2>&1
!apt-get install -f > /dev/null 2>&1
!rm -rf google-chrome-stable_current_amd64.deb > /dev/null 2>&1

# Dowload WebDriver
!wget https://chromedriver.storage.googleapis.com/version_ok/chromedriver_linux64.zip > /dev/null 2>&1
!unzip chromedriver_linux64 > /dev/null 2>&1
!rm -rf chromedriver_linux64.zip > /dev/null 2>&1
!rm -rf LICENSE.chromedriver > /dev/null 2>&1
